#!/usr/bin/env python3
"""
The app's colour palette, in one place.

Upstream ships a Material Theme Builder blue and, on Android 12+, hands the
whole theme to the wallpaper. Both read as "generic Android app". This is a
single curated Material 3 token set — warm charcoal surfaces, amber primary,
sand secondary, muted teal tertiary — applied to:

  * upstream's `md_theme_*` colour resources (light and night), by
    `apply_to_checkout()`, called from integrate.py, and
  * the Compose screens in :extras, through `Palette.kt`, regenerated by
    `python integrate/palette.py --kotlin` and committed.

Every token is listed for both modes so nothing falls back to upstream's blue.
The album-tinted player is untouched: it seeds its own colours from the cover.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

DARK = {
    "primary": "#F5B84B",
    "onPrimary": "#402D00",
    "primaryContainer": "#5C4300",
    "onPrimaryContainer": "#FFDF9E",
    "secondary": "#D4C4A8",
    "onSecondary": "#3A2F1B",
    "secondaryContainer": "#4A3F2E",
    "onSecondaryContainer": "#F1E4CC",
    "tertiary": "#86D0C6",
    "onTertiary": "#003733",
    "tertiaryContainer": "#1F4F4A",
    "onTertiaryContainer": "#A4ECE2",
    "error": "#FFB4AB",
    "onError": "#690005",
    "errorContainer": "#93000A",
    "onErrorContainer": "#FFDAD6",
    "background": "#0F1014",
    "onBackground": "#ECE9E4",
    "surface": "#0F1014",
    "onSurface": "#ECE9E4",
    "surfaceVariant": "#2F3138",
    "onSurfaceVariant": "#B3AFA8",
    "outline": "#8E8A83",
    "outlineVariant": "#45433F",
    "inverseSurface": "#ECE9E4",
    "inverseOnSurface": "#2F3138",
    "inversePrimary": "#7A5900",
    "primaryFixed": "#FFDF9E",
    "onPrimaryFixed": "#271900",
    "primaryFixedDim": "#F5B84B",
    "onPrimaryFixedVariant": "#5C4300",
    "secondaryFixed": "#F1E4CC",
    "onSecondaryFixed": "#241A0A",
    "secondaryFixedDim": "#D4C4A8",
    "onSecondaryFixedVariant": "#4A3F2E",
    "tertiaryFixed": "#A4ECE2",
    "onTertiaryFixed": "#00201D",
    "tertiaryFixedDim": "#86D0C6",
    "onTertiaryFixedVariant": "#1F4F4A",
    "surfaceDim": "#0F1014",
    "surfaceBright": "#35373D",
    "surfaceContainerLowest": "#0A0B0E",
    "surfaceContainerLow": "#16171C",
    "surfaceContainer": "#1B1C22",
    "surfaceContainerHigh": "#25272E",
    "surfaceContainerHighest": "#2F3138",
}

LIGHT = {
    "primary": "#7A5900",
    "onPrimary": "#FFFFFF",
    "primaryContainer": "#FFDF9E",
    "onPrimaryContainer": "#271900",
    "secondary": "#6B5D45",
    "onSecondary": "#FFFFFF",
    "secondaryContainer": "#F4E1C2",
    "onSecondaryContainer": "#241A0A",
    "tertiary": "#3C6660",
    "onTertiary": "#FFFFFF",
    "tertiaryContainer": "#BEEBE3",
    "onTertiaryContainer": "#00201D",
    "error": "#BA1A1A",
    "onError": "#FFFFFF",
    "errorContainer": "#FFDAD6",
    "onErrorContainer": "#410002",
    "background": "#FBF8F3",
    "onBackground": "#1C1B18",
    "surface": "#FBF8F3",
    "onSurface": "#1C1B18",
    "surfaceVariant": "#E9E3D8",
    "onSurfaceVariant": "#4D4739",
    "outline": "#7E7667",
    "outlineVariant": "#D0C5B4",
    "inverseSurface": "#31302D",
    "inverseOnSurface": "#F3F0EA",
    "inversePrimary": "#F5B84B",
    "primaryFixed": "#FFDF9E",
    "onPrimaryFixed": "#271900",
    "primaryFixedDim": "#F5B84B",
    "onPrimaryFixedVariant": "#5C4300",
    "secondaryFixed": "#F1E4CC",
    "onSecondaryFixed": "#241A0A",
    "secondaryFixedDim": "#D4C4A8",
    "onSecondaryFixedVariant": "#4A3F2E",
    "tertiaryFixed": "#A4ECE2",
    "onTertiaryFixed": "#00201D",
    "tertiaryFixedDim": "#86D0C6",
    "onTertiaryFixedVariant": "#1F4F4A",
    "surfaceDim": "#DCD9D3",
    "surfaceBright": "#FBF8F3",
    "surfaceContainerLowest": "#FFFFFF",
    "surfaceContainerLow": "#F5F2EC",
    "surfaceContainer": "#EFECE6",
    "surfaceContainerHigh": "#E9E6E0",
    "surfaceContainerHighest": "#E3E0DA",
}

# Splash and launcher backgrounds live outside the md_theme_ set.
EXTRA_DARK = {"splash_foreground_color": "#F5B84B"}
EXTRA_LIGHT = {"splash_foreground_color": "#7A5900"}


def _apply(path: Path, tokens: dict[str, str], extra: dict[str, str]) -> int:
    text = path.read_text(encoding="utf-8")
    changed = 0
    for name, value in list(tokens.items()) + list(extra.items()):
        res_name = name if name in extra else f"md_theme_{name}"
        pattern = re.compile(rf'(<color name="{re.escape(res_name)}">)#[0-9A-Fa-f]{{6,8}}(</color>)')
        text, n = pattern.subn(rf"\g<1>{value}\g<2>", text)
        changed += n
    path.write_text(text, encoding="utf-8", newline="\n")
    return changed


def apply_to_checkout(root: Path) -> list[str]:
    res = root / "app" / "src" / "main" / "res"
    n_light = _apply(res / "values" / "colors.xml", LIGHT, EXTRA_LIGHT)
    n_dark = _apply(res / "values-night" / "colors.xml", DARK, EXTRA_DARK)
    if n_light < len(LIGHT) or n_dark < len(DARK):
        raise RuntimeError(
            f"palette: expected to rewrite {len(LIGHT)}/{len(DARK)} colours, "
            f"rewrote {n_light}/{n_dark}; upstream colors.xml has changed shape"
        )
    return [
        f"  + values/colors.xml: {n_light} colours",
        f"  + values-night/colors.xml: {n_dark} colours",
    ]


def kotlin() -> str:
    def scheme(name: str, tokens: dict[str, str]) -> str:
        # Compose's ColorScheme has no *Fixed* roles; those only exist for
        # the View theme.
        lines = [f"    {k} = Color(0xFF{v[1:]})," for k, v in tokens.items() if "Fixed" not in k]
        return f"internal val {name} = {name.replace('Palette', '').lower()}ColorScheme(\n" + "\n".join(lines) + "\n)"

    return (
        "/*\n"
        " * Generated by integrate/palette.py — edit the palette there, then run\n"
        " *   python integrate/palette.py --kotlin\n"
        " * Same tokens as upstream's md_theme_* resources, so Compose screens match\n"
        " * the View-based ones exactly.\n"
        " */\n\n"
        "package org.akanework.gramophone.extras.ui\n\n"
        "import androidx.compose.material3.darkColorScheme\n"
        "import androidx.compose.material3.lightColorScheme\n"
        "import androidx.compose.ui.graphics.Color\n\n"
        + scheme("DarkPalette", DARK) + "\n\n" + scheme("LightPalette", LIGHT) + "\n"
    )


if __name__ == "__main__":
    if "--kotlin" in sys.argv:
        out = Path(__file__).resolve().parent.parent / "extras" / "src" / "main" / "java" / \
            "org" / "akanework" / "gramophone" / "extras" / "ui" / "Palette.kt"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(kotlin(), encoding="utf-8", newline="\n")
        print(f"wrote {out}")
    else:
        print("usage: palette.py --kotlin   (integrate.py applies the resources)")
