#!/usr/bin/env python3
"""
The app's colour palette, in one place.

Upstream ships a Material Theme Builder blue and, on Android 12+, hands the
whole theme to the wallpaper. Both read as "generic Android app". This is a
single curated Material 3 token set — near-black surfaces, the Spotify green
(#1DB954 / #1ED760) as primary with black on it, grey secondary — applied to:

  * upstream's `md_theme_*` colour resources (light and night), by
    `apply_to_checkout()`, called from integrate.py, and
  * the Compose screens in :extras, through `Palette.kt`, regenerated by
    `python integrate/palette.py --kotlin` and committed.

Every token is listed for both modes so nothing falls back to upstream's blue.
The album-tinted player is untouched: it seeds its own colours from the cover.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

DARK = {
    "primary": "#1ED760",
    "onPrimary": "#000000",
    "primaryContainer": "#14532D",
    "onPrimaryContainer": "#B7F5CB",
    "secondary": "#B3B3B3",
    "onSecondary": "#000000",
    "secondaryContainer": "#1DB954",
    "onSecondaryContainer": "#000000",
    "tertiary": "#1ED760",
    "onTertiary": "#000000",
    "tertiaryContainer": "#1B3D25",
    "onTertiaryContainer": "#B7F5CB",
    "error": "#F15E6C",
    "onError": "#000000",
    "errorContainer": "#5C1F27",
    "onErrorContainer": "#FFDAD6",
    "background": "#121212",
    "onBackground": "#FFFFFF",
    "surface": "#121212",
    "onSurface": "#FFFFFF",
    "surfaceVariant": "#2A2A2A",
    "onSurfaceVariant": "#B3B3B3",
    "outline": "#727272",
    "outlineVariant": "#3E3E3E",
    "inverseSurface": "#FFFFFF",
    "inverseOnSurface": "#121212",
    "inversePrimary": "#117A37",
    "primaryFixed": "#B7F5CB",
    "onPrimaryFixed": "#00210B",
    "primaryFixedDim": "#1ED760",
    "onPrimaryFixedVariant": "#0F7A3A",
    "secondaryFixed": "#E0E0E0",
    "onSecondaryFixed": "#1A1A1A",
    "secondaryFixedDim": "#B3B3B3",
    "onSecondaryFixedVariant": "#4A4A4A",
    "tertiaryFixed": "#B7F5CB",
    "onTertiaryFixed": "#00210B",
    "tertiaryFixedDim": "#1ED760",
    "onTertiaryFixedVariant": "#0F7A3A",
    "surfaceDim": "#121212",
    "surfaceBright": "#3A3A3A",
    "surfaceContainerLowest": "#000000",
    "surfaceContainerLow": "#181818",
    "surfaceContainer": "#1F1F1F",
    "surfaceContainerHigh": "#282828",
    "surfaceContainerHighest": "#333333",
}

LIGHT = {
    "primary": "#117A37",
    "onPrimary": "#FFFFFF",
    "primaryContainer": "#B7F5CB",
    "onPrimaryContainer": "#00210B",
    "secondary": "#535353",
    "onSecondary": "#FFFFFF",
    "secondaryContainer": "#1DB954",
    "onSecondaryContainer": "#000000",
    "tertiary": "#117A37",
    "onTertiary": "#FFFFFF",
    "tertiaryContainer": "#B7F5CB",
    "onTertiaryContainer": "#00210B",
    "error": "#B3261E",
    "onError": "#FFFFFF",
    "errorContainer": "#F9DEDC",
    "onErrorContainer": "#410E0B",
    "background": "#FFFFFF",
    "onBackground": "#121212",
    "surface": "#FFFFFF",
    "onSurface": "#121212",
    "surfaceVariant": "#E6E6E6",
    "onSurfaceVariant": "#535353",
    "outline": "#757575",
    "outlineVariant": "#C4C4C4",
    "inverseSurface": "#121212",
    "inverseOnSurface": "#F5F5F5",
    "inversePrimary": "#1ED760",
    "primaryFixed": "#B7F5CB",
    "onPrimaryFixed": "#00210B",
    "primaryFixedDim": "#1ED760",
    "onPrimaryFixedVariant": "#0F7A3A",
    "secondaryFixed": "#E0E0E0",
    "onSecondaryFixed": "#1A1A1A",
    "secondaryFixedDim": "#B3B3B3",
    "onSecondaryFixedVariant": "#4A4A4A",
    "tertiaryFixed": "#B7F5CB",
    "onTertiaryFixed": "#00210B",
    "tertiaryFixedDim": "#1ED760",
    "onTertiaryFixedVariant": "#0F7A3A",
    "surfaceDim": "#E0E0E0",
    "surfaceBright": "#FFFFFF",
    "surfaceContainerLowest": "#FFFFFF",
    "surfaceContainerLow": "#F7F7F7",
    "surfaceContainer": "#F0F0F0",
    "surfaceContainerHigh": "#E8E8E8",
    "surfaceContainerHighest": "#E0E0E0",
}

# Splash and launcher backgrounds live outside the md_theme_ set.
EXTRA_DARK = {"splash_foreground_color": "#1ED760"}
EXTRA_LIGHT = {"splash_foreground_color": "#117A37"}


def _apply(path: Path, tokens: dict[str, str], extra: dict[str, str]) -> int:
    text = path.read_text(encoding="utf-8")
    changed = 0
    for name, value in list(tokens.items()) + list(extra.items()):
        res_name = name if name in extra else f"md_theme_{name}"
        pattern = re.compile(rf'(<color name="{re.escape(res_name)}">)#[0-9A-Fa-f]{{6,8}}(</color>)')
        text, n = pattern.subn(rf"\g<1>{value}\g<2>", text)
        changed += n
    path.write_text(text, encoding="utf-8", newline="\n")
    return changed


def apply_to_checkout(root: Path) -> list[str]:
    res = root / "app" / "src" / "main" / "res"
    n_light = _apply(res / "values" / "colors.xml", LIGHT, EXTRA_LIGHT)
    n_dark = _apply(res / "values-night" / "colors.xml", DARK, EXTRA_DARK)
    if n_light < len(LIGHT) or n_dark < len(DARK):
        raise RuntimeError(
            f"palette: expected to rewrite {len(LIGHT)}/{len(DARK)} colours, "
            f"rewrote {n_light}/{n_dark}; upstream colors.xml has changed shape"
        )
    return [
        f"  + values/colors.xml: {n_light} colours",
        f"  + values-night/colors.xml: {n_dark} colours",
    ]


def kotlin() -> str:
    def scheme(name: str, tokens: dict[str, str]) -> str:
        # Compose's ColorScheme has no *Fixed* roles; those only exist for
        # the View theme.
        lines = [f"    {k} = Color(0xFF{v[1:]})," for k, v in tokens.items() if "Fixed" not in k]
        return f"internal val {name} = {name.replace('Palette', '').lower()}ColorScheme(\n" + "\n".join(lines) + "\n)"

    return (
        "/*\n"
        " * Generated by integrate/palette.py — edit the palette there, then run\n"
        " *   python integrate/palette.py --kotlin\n"
        " * Same tokens as upstream's md_theme_* resources, so Compose screens match\n"
        " * the View-based ones exactly.\n"
        " */\n\n"
        "package org.akanework.gramophone.extras.ui\n\n"
        "import androidx.compose.material3.darkColorScheme\n"
        "import androidx.compose.material3.lightColorScheme\n"
        "import androidx.compose.ui.graphics.Color\n\n"
        + scheme("DarkPalette", DARK) + "\n\n" + scheme("LightPalette", LIGHT) + "\n"
    )


if __name__ == "__main__":
    if "--kotlin" in sys.argv:
        out = Path(__file__).resolve().parent.parent / "extras" / "src" / "main" / "java" / \
            "org" / "akanework" / "gramophone" / "extras" / "ui" / "Palette.kt"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(kotlin(), encoding="utf-8", newline="\n")
        print(f"wrote {out}")
    else:
        print("usage: palette.py --kotlin   (integrate.py applies the resources)")
