/*
 * Generated by integrate/palette.py — edit the palette there, then run
 *   python integrate/palette.py --kotlin
 * Same tokens as upstream's md_theme_* resources, so Compose screens match
 * the View-based ones exactly.
 */

package org.akanework.gramophone.extras.ui

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val DarkPalette = darkColorScheme(
    primary = Color(0xFFF5B84B),
    onPrimary = Color(0xFF402D00),
    primaryContainer = Color(0xFF5C4300),
    onPrimaryContainer = Color(0xFFFFDF9E),
    secondary = Color(0xFFD4C4A8),
    onSecondary = Color(0xFF3A2F1B),
    secondaryContainer = Color(0xFF4A3F2E),
    onSecondaryContainer = Color(0xFFF1E4CC),
    tertiary = Color(0xFF86D0C6),
    onTertiary = Color(0xFF003733),
    tertiaryContainer = Color(0xFF1F4F4A),
    onTertiaryContainer = Color(0xFFA4ECE2),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0F1014),
    onBackground = Color(0xFFECE9E4),
    surface = Color(0xFF0F1014),
    onSurface = Color(0xFFECE9E4),
    surfaceVariant = Color(0xFF2F3138),
    onSurfaceVariant = Color(0xFFB3AFA8),
    outline = Color(0xFF8E8A83),
    outlineVariant = Color(0xFF45433F),
    inverseSurface = Color(0xFFECE9E4),
    inverseOnSurface = Color(0xFF2F3138),
    inversePrimary = Color(0xFF7A5900),
    surfaceDim = Color(0xFF0F1014),
    surfaceBright = Color(0xFF35373D),
    surfaceContainerLowest = Color(0xFF0A0B0E),
    surfaceContainerLow = Color(0xFF16171C),
    surfaceContainer = Color(0xFF1B1C22),
    surfaceContainerHigh = Color(0xFF25272E),
    surfaceContainerHighest = Color(0xFF2F3138),
)

internal val LightPalette = lightColorScheme(
    primary = Color(0xFF7A5900),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDF9E),
    onPrimaryContainer = Color(0xFF271900),
    secondary = Color(0xFF6B5D45),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF4E1C2),
    onSecondaryContainer = Color(0xFF241A0A),
    tertiary = Color(0xFF3C6660),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBEEBE3),
    onTertiaryContainer = Color(0xFF00201D),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFBF8F3),
    onBackground = Color(0xFF1C1B18),
    surface = Color(0xFFFBF8F3),
    onSurface = Color(0xFF1C1B18),
    surfaceVariant = Color(0xFFE9E3D8),
    onSurfaceVariant = Color(0xFF4D4739),
    outline = Color(0xFF7E7667),
    outlineVariant = Color(0xFFD0C5B4),
    inverseSurface = Color(0xFF31302D),
    inverseOnSurface = Color(0xFFF3F0EA),
    inversePrimary = Color(0xFFF5B84B),
    surfaceDim = Color(0xFFDCD9D3),
    surfaceBright = Color(0xFFFBF8F3),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF5F2EC),
    surfaceContainer = Color(0xFFEFECE6),
    surfaceContainerHigh = Color(0xFFE9E6E0),
    surfaceContainerHighest = Color(0xFFE3E0DA),
)
