/*
 * Generated by integrate/palette.py — edit the palette there, then run
 *   python integrate/palette.py --kotlin
 * Same tokens as upstream's md_theme_* resources, so Compose screens match
 * the View-based ones exactly.
 */

package org.akanework.gramophone.extras.ui

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val DarkPalette = darkColorScheme(
    primary = Color(0xFF1ED760),
    onPrimary = Color(0xFF000000),
    primaryContainer = Color(0xFF14532D),
    onPrimaryContainer = Color(0xFFB7F5CB),
    secondary = Color(0xFFB3B3B3),
    onSecondary = Color(0xFF000000),
    secondaryContainer = Color(0xFF1DB954),
    onSecondaryContainer = Color(0xFF000000),
    tertiary = Color(0xFF1ED760),
    onTertiary = Color(0xFF000000),
    tertiaryContainer = Color(0xFF1B3D25),
    onTertiaryContainer = Color(0xFFB7F5CB),
    error = Color(0xFFF15E6C),
    onError = Color(0xFF000000),
    errorContainer = Color(0xFF5C1F27),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF121212),
    onBackground = Color(0xFFFFFFFF),
    surface = Color(0xFF121212),
    onSurface = Color(0xFFFFFFFF),
    surfaceVariant = Color(0xFF2A2A2A),
    onSurfaceVariant = Color(0xFFB3B3B3),
    outline = Color(0xFF727272),
    outlineVariant = Color(0xFF3E3E3E),
    inverseSurface = Color(0xFFFFFFFF),
    inverseOnSurface = Color(0xFF121212),
    inversePrimary = Color(0xFF117A37),
    surfaceDim = Color(0xFF121212),
    surfaceBright = Color(0xFF3A3A3A),
    surfaceContainerLowest = Color(0xFF000000),
    surfaceContainerLow = Color(0xFF181818),
    surfaceContainer = Color(0xFF1F1F1F),
    surfaceContainerHigh = Color(0xFF282828),
    surfaceContainerHighest = Color(0xFF333333),
)

internal val LightPalette = lightColorScheme(
    primary = Color(0xFF117A37),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB7F5CB),
    onPrimaryContainer = Color(0xFF00210B),
    secondary = Color(0xFF535353),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFF1DB954),
    onSecondaryContainer = Color(0xFF000000),
    tertiary = Color(0xFF117A37),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFB7F5CB),
    onTertiaryContainer = Color(0xFF00210B),
    error = Color(0xFFB3261E),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF9DEDC),
    onErrorContainer = Color(0xFF410E0B),
    background = Color(0xFFFFFFFF),
    onBackground = Color(0xFF121212),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF121212),
    surfaceVariant = Color(0xFFE6E6E6),
    onSurfaceVariant = Color(0xFF535353),
    outline = Color(0xFF757575),
    outlineVariant = Color(0xFFC4C4C4),
    inverseSurface = Color(0xFF121212),
    inverseOnSurface = Color(0xFFF5F5F5),
    inversePrimary = Color(0xFF1ED760),
    surfaceDim = Color(0xFFE0E0E0),
    surfaceBright = Color(0xFFFFFFFF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF7F7F7),
    surfaceContainer = Color(0xFFF0F0F0),
    surfaceContainerHigh = Color(0xFFE8E8E8),
    surfaceContainerHighest = Color(0xFFE0E0E0),
)
